### PR TITLE
replace event_location with event_venue

### PR DESCRIPTION
**Pull request by binary1230**
- we added c.EVENT_VENUE in base uber over the summer, so it can replace the same INI setting from the panels plugin

### CODE REVIEW

**Comment by binary1230** [comment]
goes with https://github.com/magfest/ubersystem-puppet/pull/97

**Comment by kitsuta** [comment]
+1

**Comment by RobRuana** [comment]
Ok – aside from the merge conflicts – this still good? Can we just merge this and everything will be fine?

**Comment by kitsuta** [comment]
From my read this should be okay to merge! It looks like we had `c.EVENT_LOCATION` configured in this plugin and only used in this plugin, and then only in the one place. I did a search of the current state of the repo to make sure.

**Comment by RobRuana** [comment]
Okay, I've done some digging and there are a few more places where we are using `EVENT_LOCATION`. Just a few. I'm gonna quick update this pull-request so we can merge it, and then we can merge this: https://github.com/magfest/ubersystem-puppet/pull/97.

Trying to clean up some old pull requests...

**Comment by RobRuana** [comment]
~Ok, this pull request is so old that I'm getting a bunch of errors when I load up the branch. I'm going to close this pull request and open a new one based off the current master. (There's probably some rebase magic I could do, but I'm doing the quick-n-dirty thing)~

Nevermind! This looks good!

**Pull request merged**
